/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all active sessions */
        get: operations["listSessions"];
        put?: never;
        /** Create a new visualization session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get session snapshot with coroutine state */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Close and delete a session */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all events for a session */
        get: operations["getSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get coroutine hierarchy tree for a session */
        get: operations["getSessionHierarchy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get thread activity data for a session */
        get: operations["getSessionThreadActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/coroutines/{coroutineId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get timeline for a specific coroutine */
        get: operations["getCoroutineTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all available scenarios */
        get: operations["listScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/nested": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run nested coroutines scenario */
        post: operations["runNestedScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/parallel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run parallel execution scenario */
        post: operations["runParallelScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run cancellation scenario */
        post: operations["runCancellationScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/deep-nesting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run deep nesting scenario */
        post: operations["runDeepNestingScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/mixed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run mixed sequential/parallel scenario */
        post: operations["runMixedScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/exception": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run exception handling scenario */
        post: operations["runExceptionScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/channel-rendezvous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run channel rendezvous scenario */
        post: operations["runChannelRendezvousScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/channel-buffered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run channel buffered scenario */
        post: operations["runChannelBufferedScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/channel-fan-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run channel fan-out scenario */
        post: operations["runChannelFanOutScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/order-processing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run order processing scenario */
        post: operations["runOrderProcessingScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/user-registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run user registration scenario */
        post: operations["runUserRegistrationScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/report-generation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run report generation scenario */
        post: operations["runReportGenerationScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a custom user-defined scenario */
        post: operations["runCustomScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate/session/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run validation rules against a session's events */
        post: operations["validateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all available validation rules */
        get: operations["listValidationRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionInfo: {
            sessionId: string;
            coroutineCount: number;
            eventCount: number;
        };
        CreateSessionResponse: {
            sessionId: string;
            message: string;
        };
        MessageResponse: {
            message: string;
        };
        ErrorResponse: {
            error: string;
        };
        /** @enum {string} */
        CoroutineState: "CREATED" | "ACTIVE" | "SUSPENDED" | "WAITING_FOR_CHILDREN" | "COMPLETED" | "CANCELLED" | "FAILED";
        CoroutineNodeDto: {
            id: string;
            jobId: string;
            parentId?: string | null;
            scopeId: string;
            label?: string | null;
            state: string;
        };
        SessionSnapshotResponse: {
            sessionId: string;
            coroutineCount: number;
            eventCount: number;
            coroutines: components["schemas"]["CoroutineNodeDto"][];
        };
        HierarchyNode: {
            id: string;
            parentId?: string | null;
            /** @default [] */
            children: string[];
            name: string;
            scopeId: string;
            state: string;
            /** Format: int64 */
            createdAtNanos: number;
            /** Format: int64 */
            completedAtNanos?: number | null;
            dispatcherId?: string | null;
            dispatcherName?: string | null;
            /** Format: int64 */
            currentThreadId?: number | null;
            currentThreadName?: string | null;
            jobId: string;
            exceptionType?: string | null;
            exceptionMessage?: string | null;
            /** @default [] */
            activeChildrenIds: string[];
            /** @default 0 */
            activeChildrenCount: number;
        };
        CoroutineTimeline: {
            coroutineId: string;
            name: string;
            state: string;
            /**
             * Format: int64
             * @description Total time from creation to completion in nanoseconds
             */
            totalDuration?: number | null;
            /**
             * Format: int64
             * @description Time spent actively running in nanoseconds
             */
            activeDuration?: number | null;
            /**
             * Format: int64
             * @description Time spent suspended in nanoseconds
             */
            suspendedDuration?: number | null;
            parentId?: string | null;
            /** @default [] */
            childrenIds: string[];
            /** @default [] */
            events: components["schemas"]["TimelineEventSummary"][];
        };
        TimelineEventSummary: {
            /** Format: int64 */
            seq: number;
            /** Format: int64 */
            tsNanos: number;
            kind: string;
            threadName?: string | null;
            dispatcherName?: string | null;
            /** @description For suspension events */
            reason?: string | null;
        };
        ThreadEvent: {
            coroutineId: string;
            /** Format: int64 */
            threadId: number;
            threadName: string;
            /** Format: int64 */
            timestamp: number;
            /** @enum {string} */
            eventType: "ASSIGNED" | "RELEASED";
            dispatcherName?: string | null;
        };
        Scenario: {
            id: string;
            name: string;
            description: string;
            endpoint: string;
            /** @enum {string} */
            category?: "realistic" | "channel" | "basic";
            duration?: string | null;
        };
        ScenarioListResponse: {
            scenarios: components["schemas"]["Scenario"][];
        };
        ScenarioCompletionResponse: {
            success: boolean;
            sessionId: string;
            message: string;
            coroutineCount: number;
            eventCount: number;
        };
        ActionDTO: {
            /** @enum {string} */
            type: "delay" | "throw" | "log" | "custom";
            /** @default {} */
            params: {
                [key: string]: string;
            };
        };
        CoroutineConfigDTO: {
            id: string;
            label: string;
            parentId?: string | null;
            /** @default [] */
            actions: components["schemas"]["ActionDTO"][];
            /** @default [] */
            children: components["schemas"]["CoroutineConfigDTO"][];
        };
        ScenarioConfigRequest: {
            name: string;
            description?: string | null;
            sessionId?: string | null;
            root: components["schemas"]["CoroutineConfigDTO"];
        };
        ScenarioExecutionResponse: {
            success: boolean;
            sessionId: string;
            message: string;
            /** @default 0 */
            coroutineCount: number;
            /** @default 0 */
            eventCount: number;
            errors?: string[] | null;
        };
        ValidationResponse: {
            sessionId: string;
            results: components["schemas"]["ValidationResult"][];
            timing: components["schemas"]["TimingReport"];
        };
        ValidationResult: {
            /** @enum {string} */
            type?: "Pass" | "Fail";
            ruleName: string;
            message: string;
            /** @description Present only for Fail results */
            details?: string;
        };
        TimingReport: {
            /** @description Map of coroutine ID to total duration in nanoseconds */
            coroutineDurations: {
                [key: string]: number;
            };
            /** @description Map of coroutine ID to list of suspension durations in nanoseconds */
            suspensionDurations: {
                [key: string]: number[];
            };
            /**
             * Format: int64
             * @description Overall duration of the event stream in nanoseconds
             */
            totalDuration: number;
        };
        ValidationRule: {
            name: string;
            description: string;
        };
        /** @description Base event shape. Actual events are polymorphic and discriminated by the 'kind' field. See events.ts for full TypeScript types. */
        VizEvent: {
            sessionId: string;
            /** Format: int64 */
            seq: number;
            /** Format: int64 */
            tsNanos: number;
            kind: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: {
                /** @description Optional session name */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshotResponse"];
                };
            };
            /** @description Missing session ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all session events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VizEvent"][];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSessionHierarchy: {
        parameters: {
            query?: {
                /** @description Optional scope ID to filter hierarchy */
                scopeId?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hierarchy tree of coroutines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HierarchyNode"][];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSessionThreadActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread activity data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ThreadEvent"][];
                    };
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCoroutineTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                coroutineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coroutine timeline with computed durations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoroutineTimeline"];
                };
            };
            /** @description Session or coroutine not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available scenarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    runNestedScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runParallelScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runCancellationScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runDeepNestingScenario: {
        parameters: {
            query?: {
                sessionId?: string;
                depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runMixedScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runExceptionScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runChannelRendezvousScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runChannelBufferedScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runChannelFanOutScenario: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runOrderProcessingScenario: {
        parameters: {
            query?: {
                sessionId?: string;
                /** @description Simulate payment failure */
                fail?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runUserRegistrationScenario: {
        parameters: {
            query?: {
                sessionId?: string;
                /** @description Simulate email failure with retry */
                failEmail?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runReportGenerationScenario: {
        parameters: {
            query?: {
                sessionId?: string;
                /** @description Simulate API timeout */
                timeout?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCompletionResponse"];
                };
            };
            /** @description Scenario failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runCustomScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioConfigRequest"];
            };
        };
        responses: {
            /** @description Scenario completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioExecutionResponse"];
                };
            };
            /** @description Invalid scenario configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioExecutionResponse"];
                };
            };
            /** @description Scenario execution error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioExecutionResponse"];
                };
            };
        };
    };
    validateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listValidationRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of validation rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRule"][];
                };
            };
        };
    };
}
